### PR TITLE
refactor to let catch more than just cites (useful when using packages l...

### PR DESCRIPTION
**Pull request by gidden**
...ike biblatex

Specifically, I'm starting to use things like `\fullcite{my_citation_handle}` which this now picks up

### CODE REVIEW

**Comment by elliottbiondo** [comment]
Hmmm this seems to break for:

\cite{citation1, citation2}

**Comment by gidden** [comment]
updated. wana write some tests?!

On Sat, Apr 18, 2015 at 1:11 PM, Elliott Biondo notifications@github.com
wrote:

> Hmmm this seems to break for:
> 
> \cite{citation1, citation2}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elliottbiondo/zo/pull/9#issuecomment-94188321.

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by elliottbiondo** [comment]
Yes I do.

**Comment by gidden** [comment]
this works, btw

On Tue, May 5, 2015 at 12:58 PM, Elliott Biondo notifications@github.com
wrote:

> Yes I do.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/elliottbiondo/zo/pull/9#issuecomment-99159080.

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by elliottbiondo** [comment]
Great, I am testing it on my prelim right now.

**Comment by elliottbiondo** [comment]
Works great. setup.py + tests are on the horizon. Merged. Thanks!

**Pull request merged**
